// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://entlfsztdigzgceufkwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudGxmc3p0ZGlnemdjZXVma3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzODc0MzEsImV4cCI6MjA4NTk2MzQzMX0.-0jxPO3XLTvlCWDDpBt-G7GzPHldAINpL_vQvoMSC1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});